#pragma once
#include "Lunib/Core/base.h"


namespace Lunib::Math
{
	enum ClipControl
	{
		LUNIB_CLIP_CONTROL_ZO_BIT = BIT(0),
		LUNIB_CLIP_CONTROL_NO_BIT = BIT(1),
		LUNIB_CLIP_CONTROL_LH_BIT = BIT(2),
		LUNIB_CLIP_CONTROL_RH_BIT = BIT(3),

		LUNIB_CLIP_CONTROL_LH_ZO = LUNIB_CLIP_CONTROL_LH_BIT | LUNIB_CLIP_CONTROL_ZO_BIT,
		LUNIB_CLIP_CONTROL_LH_NO = LUNIB_CLIP_CONTROL_LH_BIT | LUNIB_CLIP_CONTROL_NO_BIT,
		LUNIB_CLIP_CONTROL_RH_ZO = LUNIB_CLIP_CONTROL_RH_BIT | LUNIB_CLIP_CONTROL_ZO_BIT,
		LUNIB_CLIP_CONTROL_RH_NO = LUNIB_CLIP_CONTROL_RH_BIT | LUNIB_CLIP_CONTROL_NO_BIT
	};

	#ifndef LUNIB_CONFIG_CLIP_CONTROL
		#ifdef LUNIB_FORCE_DEPTH_ZERO_TO_ONE
			#ifdef LUNIB_FORCE_LEFT_HANDED
				#define LUNIB_CONFIG_CLIP_CONTROL LUNIB_CLIP_CONTROL_LH_ZO
			#else
				#define LUNIB_CONFIG_CLIP_CONTROL LUNIB_CLIP_CONTROL_RH_ZO
			#endif
		#else
			#ifdef LUNIB_FORCE_LEFT_HANDED
				#define LUNIB_CONFIG_CLIP_CONTROL LUNIB_CLIP_CONTROL_LH_NO
			#else
				#define LUNIB_CONFIG_CLIP_CONTROL LUNIB_CLIP_CONTROL_RH_NO
			#endif
		#endif
	#endif

} // Lunib::Math